name: xue_hua_speaker_earpiece_toggle
description: "A Flutter plugin to toggle between speaker and earpiece audio routes on Android and iOS."
version: 1.1.0
homepage: https://github.com/Matkurban/xue_hua_speaker_earpiece_toggle
repository: https://github.com/Matkurban/xue_hua_speaker_earpiece_toggle
issue_tracker: https://github.com/Matkurban/xue_hua_speaker_earpiece_toggle/issues
documentation: https://github.com/Matkurban/xue_hua_speaker_earpiece_toggle/blob/main/README.md

environment:
  sdk: ^3.12.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kurban.xue_hua_speaker_earpiece_toggle
        pluginClass: XueHuaSpeakerEarpieceTogglePlugin
      ios:
        pluginClass: XueHuaSpeakerEarpieceTogglePlugin
